# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deep Learning
email: narayana.anantharaman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Deep Learning techniques have powered innumerable novel applications and I believe this is just the beginning. There have been quite a number of wonderful blogs and articles on this exciting subject. This blog is a humble attempt at sharing my experiences as an entrepreneur and also as a faculty advising student projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ananthpn
github_username:  ananthpn

# Build settings
markdown: kramdown
